# Generated by Django 3.0.2 on 2020-01-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=25, unique=True)),
                ('mileage', models.CharField(max_length=11)),
                ('user_type', models.IntegerField(choices=[(1, 'Hospital'), (2, 'Vendor')], default=1, verbose_name='user_type')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Booked')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='deteted at')),
                ('deleted_by_id', models.IntegerField(blank=True, null=True, verbose_name='deteted by')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCategory')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
